import { useEffect, useMemo, useState } from 'react'
import type { FormEvent } from 'react'

import {
  deleteSavedCredential,
  getHealth,
  getSavedCredentials,
  saveOneKey,
} from '../api.ts'
import type { Health, SaveOneKeyDraft, SavedCredential } from '../types.ts'

const defaultDraft: SaveOneKeyDraft = {
  displayName: 'Remote Proxy',
  oneKey: '',
}

const credentialPreview = (credential: string): string =>
  `${credential.slice(0, 8)}...${credential.slice(Math.max(0, credential.length - 8))}`

const formatTriedAddresses = (addresses: string[]): string =>
  addresses.map((address, index) => `${index + 1}. ${address}`).join('\n')

export function OneKeyPage() {
  const [health, setHealth] = useState<Health | null>(null)
  const [credentials, setCredentials] = useState<SavedCredential[]>([])
  const [draft, setDraft] = useState<SaveOneKeyDraft>(defaultDraft)
  const [busyDeleteId, setBusyDeleteId] = useState<string | null>(null)
  const [loading, setLoading] = useState(true)
  const [submitting, setSubmitting] = useState(false)
  const [notice, setNotice] = useState<string | null>(null)
  const [error, setError] = useState<string | null>(null)

  const loadAll = async (): Promise<void> => {
    try {
      const [nextHealth, nextCredentials] = await Promise.all([
        getHealth(),
        getSavedCredentials(),
      ])

      setHealth(nextHealth)
      setCredentials(nextCredentials)
      setError(null)
    } catch (loadError) {
      setError(loadError instanceof Error ? loadError.message : 'Failed to load OneKey data')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    void loadAll()
    const timer = window.setInterval(() => {
      void loadAll()
    }, 15000)

    return () => {
      window.clearInterval(timer)
    }
  }, [])

  const uniqueRemoteHosts = useMemo(() => {
    if (credentials.length === 0) {
      return 0
    }

    const unique = new Set(
      credentials.map((entry) => {
        try {
          const parsed = new URL(entry.reachableAddress)
          return `${parsed.hostname}:${parsed.port}`
        } catch {
          return entry.reachableAddress
        }
      }),
    )

    return unique.size
  }, [credentials])

  const uniqueCredentials = useMemo(() => {
    return new Set(credentials.map((entry) => entry.credential)).size
  }, [credentials])

  const onSaveOneKey = async (event: FormEvent<HTMLFormElement>): Promise<void> => {
    event.preventDefault()
    setSubmitting(true)
    setNotice(null)
    setError(null)

    try {
      const result = await saveOneKey(draft)
      setDraft(defaultDraft)

      if (result.skipped.length > 0) {
        setNotice(
          `${result.created.length} credential(s) added, ${result.skipped.length} duplicate address(es) skipped.`,
        )
      } else if (result.unreachableAddresses.length > 0 && result.connectedAddress) {
        setNotice(
          `${result.created.length} credential(s) added. Connected via ${result.connectedAddress} after ${result.unreachableAddresses.length} unreachable address(es).`,
        )
      } else {
        setNotice(`${result.created.length} credential(s) added successfully.`)
      }

      await loadAll()

      if (result.connectedAddress) {
        const triedAddresses =
          result.attemptedAddresses.length > 0
            ? `\nTried addresses in order:\n${formatTriedAddresses(result.attemptedAddresses)}`
            : ''

        setError(`Connected via ${result.connectedAddress}.${triedAddresses}`)
      }
    } catch (submitError) {
      setError(submitError instanceof Error ? submitError.message : 'Failed to save OneKey')
    } finally {
      setSubmitting(false)
    }
  }

  const onDeleteCredential = async (id: string): Promise<void> => {
    setBusyDeleteId(id)

    try {
      await deleteSavedCredential(id)
      await loadAll()
    } catch (deleteError) {
      setError(deleteError instanceof Error ? deleteError.message : 'Failed to delete credential')
    } finally {
      setBusyDeleteId(null)
    }
  }

  return (
    <>
      <header className="panel animate-rise overflow-hidden p-6" style={{ animationDelay: '30ms' }}>
        <p className="font-mono text-xs uppercase tracking-[0.35em] text-blue/80">Transparent Cloud Proxy</p>
        <div className="mt-3 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
          <h1 className="font-heading text-3xl text-white sm:text-4xl">OneKey Credential Dashboard</h1>
          <div className="rounded-lg border border-orange/40 bg-orange/10 px-3 py-2 font-mono text-xs text-orange">
            Node API + React + Tailwind
          </div>
        </div>
        <p className="mt-3 max-w-3xl text-sm text-slate-300">
          Add and manage OneKey credentials generated by TransparentCloudServerProxy installation. Each OneKey is
          decoded into one or more reachable proxy addresses and stored by the API.
        </p>
      </header>

      {notice && (
        <div className="animate-rise rounded-xl border border-blue/50 bg-blue/10 p-3 text-sm text-blue" role="status">
          {notice}
        </div>
      )}

      {error && (
        <div className="animate-rise whitespace-pre-wrap rounded-xl border border-orange/50 bg-orange/10 p-3 text-sm text-orange" role="alert">
          {error}
        </div>
      )}

      <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <article className="panel animate-rise p-4" style={{ animationDelay: '70ms' }}>
          <p className="text-xs uppercase tracking-[0.2em] text-blue/80">Stored Endpoints</p>
          <p className="mt-3 font-heading text-3xl text-white">{credentials.length}</p>
          <p className="mt-1 text-sm text-slate-300">saved reachable addresses</p>
        </article>
        <article className="panel animate-rise p-4" style={{ animationDelay: '120ms' }}>
          <p className="text-xs uppercase tracking-[0.2em] text-blue/80">Unique Remote Hosts</p>
          <p className="mt-3 font-heading text-3xl text-white">{uniqueRemoteHosts}</p>
          <p className="mt-1 text-sm text-slate-300">deduped host:port targets</p>
        </article>
        <article className="panel animate-rise p-4" style={{ animationDelay: '170ms' }}>
          <p className="text-xs uppercase tracking-[0.2em] text-blue/80">Credential Keys</p>
          <p className="mt-3 font-heading text-3xl text-white">{uniqueCredentials}</p>
          <p className="mt-1 text-sm text-slate-300">distinct 64-char credentials</p>
        </article>
        <article className="panel animate-rise p-4" style={{ animationDelay: '220ms' }}>
          <p className="text-xs uppercase tracking-[0.2em] text-blue/80">Gateway Health</p>
          <p className="mt-3 inline-flex items-center gap-2 font-heading text-2xl text-white">
            <span className="inline-flex h-2.5 w-2.5 animate-signal rounded-full bg-blue" />
            {loading ? 'Syncing' : health?.status === 'ok' ? 'Online' : 'Degraded'}
          </p>
          <p className="mt-1 text-sm text-slate-300">uptime {health?.uptimeSeconds ?? 0}s</p>
        </article>
      </section>

      <section className="grid gap-6 lg:grid-cols-[1.5fr_1fr]">
        <article className="panel animate-rise p-5" style={{ animationDelay: '260ms' }}>
          <div className="mb-4 flex items-center justify-between">
            <h2 className="font-heading text-2xl text-white">Saved Remote Proxies</h2>
            <button
              type="button"
              onClick={() => void loadAll()}
              className="rounded-lg border border-blue/40 px-3 py-1.5 text-xs font-semibold uppercase tracking-wide text-blue transition hover:bg-blue/10"
            >
              Refresh
            </button>
          </div>

          <div className="grid gap-3">
            {credentials.map((entry, index) => (
              <div
                key={entry.id}
                className="rounded-xl border border-blue/20 bg-midnight/70 p-4"
                style={{ animationDelay: `${300 + index * 40}ms` }}
              >
                <div className="flex flex-wrap items-center justify-between gap-2">
                  <p className="font-heading text-lg text-white">{entry.displayName}</p>
                  <p className="font-mono text-xs text-slate-400">OneKey ...{entry.sourceOneKeySuffix}</p>
                </div>
                <p className="mt-2 font-mono text-sm text-slate-200">{entry.reachableAddress}</p>
                <p className="mt-2 text-xs uppercase tracking-wider text-slate-400">
                  Credential {credentialPreview(entry.credential)}
                </p>
                <p className="mt-2 text-xs text-slate-400">Added {new Date(entry.createdAt).toLocaleString()}</p>
                <button
                  type="button"
                  onClick={() => void onDeleteCredential(entry.id)}
                  disabled={busyDeleteId === entry.id}
                  className="mt-3 rounded-lg bg-orange px-3 py-1.5 text-xs font-bold uppercase tracking-wider text-black transition hover:brightness-110 disabled:cursor-not-allowed disabled:opacity-50"
                >
                  {busyDeleteId === entry.id ? 'Removing...' : 'Remove'}
                </button>
              </div>
            ))}

            {credentials.length === 0 && (
              <p className="text-sm text-slate-300">No OneKey credentials have been saved yet.</p>
            )}
          </div>
        </article>

        <article className="panel animate-rise p-5" style={{ animationDelay: '290ms' }}>
          <h2 className="font-heading text-2xl text-white">Add OneKey</h2>
          <p className="mt-2 text-sm text-slate-300">
            Paste the OneKey from TransparentCloudServerProxy setup logs. The API decodes and stores each reachable
            server address with its credential.
          </p>

          <form className="mt-4 grid gap-3" onSubmit={(event) => void onSaveOneKey(event)}>
            <input
              className="field"
              placeholder="Display name"
              value={draft.displayName}
              onChange={(event) => setDraft((state) => ({ ...state, displayName: event.target.value }))}
            />
            <textarea
              className="field"
              placeholder="Paste OneKey"
              rows={8}
              value={draft.oneKey}
              onChange={(event) => setDraft((state) => ({ ...state, oneKey: event.target.value }))}
            />

            <button
              type="submit"
              disabled={submitting}
              className="rounded-xl bg-blue px-4 py-2 font-semibold text-white transition hover:brightness-110 disabled:cursor-not-allowed disabled:opacity-60"
            >
              {submitting ? 'Saving...' : 'Save OneKey'}
            </button>
          </form>
        </article>
      </section>

      <section className="panel animate-rise p-5" style={{ animationDelay: '320ms' }}>
        <div className="mb-4 flex flex-wrap items-center justify-between gap-2">
          <h2 className="font-heading text-2xl text-white">OneKey Format</h2>
          <p className="font-mono text-xs uppercase tracking-[0.28em] text-blue/80">C# Compatible Decode</p>
        </div>
        <div className="grid gap-2 font-mono text-xs text-slate-300">
          <p>OneKey = [64-char credential hex] + [hex UTF8 string of reachable URLs]</p>
          <p>Example URL sequence: https://10.0.0.5:5225https://public-host:5225http://10.0.0.5:5000</p>
          <p>The API normalizes each URL and stores one credential record per reachable address.</p>
        </div>
      </section>
    </>
  )
}
