@TransparentCloudServerProxy.WebDashboard_HostAddress = https://localhost:7002
@sslVerify = false
@authKey = 63BC25FC74DDC4ACBA20FAB781A8BA80F7712E13CFAC6865D10F0AAC9002ABC7

### Get proxies
GET {{TransparentCloudServerProxy.WebDashboard_HostAddress}}/ProxyApi/GetProxies
Accept: application/json
Authorization: Key {{authKey}}

### Start all proxies
POST {{TransparentCloudServerProxy.WebDashboard_HostAddress}}/ProxyApi/StartAllProxies
Authorization: Key {{authKey}}

### Start proxy
POST {{TransparentCloudServerProxy.WebDashboard_HostAddress}}/ProxyApi/StartProxy
Content-Type: application/json
Authorization: Key {{authKey}}
{
  "PacketEngine": "NativeC",
  "SocketType": "Tcp",
  "ListenHost": "0.0.0.0",
  "ListenPort": 25565,
  "TargetHost": "10.0.1.222",
  "TargetPort": 25565
}

### Stop proxy
POST {{TransparentCloudServerProxy.WebDashboard_HostAddress}}/ProxyApi/StopProxy
Content-Type: application/json
Authorization: Key {{authKey}}
{
  "PacketEngine": "NativeC",
  "SocketType": "Tcp",
  "ListenHost": "0.0.0.0",
  "ListenPort": 25565,
  "TargetHost": "10.0.1.222",
  "TargetPort": 25565
}

### AddOrModifyProxy proxy entry
POST {{TransparentCloudServerProxy.WebDashboard_HostAddress}}/ProxyApi/AddOrModifyProxy
Content-Type: application/json
Authorization: Key {{authKey}}
{
  "PacketEngine": "NativeC",
  "SocketType": "Tcp",
  "ListenHost": "0.0.0.0",
  "ListenPort": 25565,
  "TargetHost": "10.0.1.222",
  "TargetPort": 25565,
  "Enabled": true
}

### Remove proxy
POST {{TransparentCloudServerProxy.WebDashboard_HostAddress}}/ProxyApi/RemoveProxy
Content-Type: application/json
Authorization: Key {{authKey}}
{
  "PacketEngine": "NativeC",
  "SocketType": "Tcp",
  "ListenHost": "0.0.0.0",
  "ListenPort": 25567,
  "TargetHost": "10.0.1.222",
  "TargetPort": 25565
}
