@TransparentCloudServerProxy.WebDashboard_HostAddress = https://localhost:7002
@sslVerify = false
@authKey = 28C3A10AAC461880BFD5D238CAF1C6636A3000CE814AFFD1BE5D4C884EB85AEE

### Get proxies
GET {{TransparentCloudServerProxy.WebDashboard_HostAddress}}/ProxyApi/GetProxies
Accept: application/json
Authorization: Key {{authKey}}

### Start all proxies
POST {{TransparentCloudServerProxy.WebDashboard_HostAddress}}/ProxyApi/StartAllProxies
Authorization: Key {{authKey}}

### Start proxy
POST {{TransparentCloudServerProxy.WebDashboard_HostAddress}}/ProxyApi/StartProxy
Content-Type: application/json
Authorization: Key {{authKey}}
{
  "PacketEngine": "NativeC",
  "SocketType": "Tcp",
  "ListenHost": "0.0.0.0",
  "ListenPort": 25567,
  "TargetHost": "10.0.1.222",
  "TargetPort": 25565
}

### Stop proxy
POST {{TransparentCloudServerProxy.WebDashboard_HostAddress}}/ProxyApi/StopProxy
Content-Type: application/json
Authorization: Key {{authKey}}
{
  "PacketEngine": "NativeC",
  "SocketType": "Tcp",
  "ListenHost": "0.0.0.0",
  "ListenPort": 25565,
  "TargetHost": "10.0.1.222",
  "TargetPort": 25565
}

### Add proxy entry
POST {{TransparentCloudServerProxy.WebDashboard_HostAddress}}/ProxyApi/AddProxy
Content-Type: application/json
Authorization: Key {{authKey}}
{
  "PacketEngine": "NativeC",
  "SocketType": "Tcp",
  "ListenHost": "0.0.0.0",
  "ListenPort": 25567,
  "TargetHost": "10.0.1.222",
  "TargetPort": 25565
}

### Remove proxy
POST {{TransparentCloudServerProxy.WebDashboard_HostAddress}}/ProxyApi/RemoveProxy
Content-Type: application/json
Authorization: Key {{authKey}}
{
  "PacketEngine": "NativeC",
  "SocketType": "Tcp",
  "ListenHost": "0.0.0.0",
  "ListenPort": 25565,
  "TargetHost": "10.0.1.222",
  "TargetPort": 25565
}
