@TransparentCloudServerProxy.WebDashboard_HostAddress = https://localhost:7002
@sslVerify = false


### Get proxies
GET {{TransparentCloudServerProxy.WebDashboard_HostAddress}}/ProxyApi/GetProxies
Accept: application/json

### Start all proxies
POST {{TransparentCloudServerProxy.WebDashboard_HostAddress}}/ProxyApi/StartAllProxies

### Start proxy
POST {{TransparentCloudServerProxy.WebDashboard_HostAddress}}/ProxyApi/StartProxy
Content-Type: application/json

{
  "listenAddress": "0.0.0.0",
  "listenPort": 25565,
  "targetAddress": "10.0.1.222",
  "targetPort": 25565
}

### Stop proxy
POST {{TransparentCloudServerProxy.WebDashboard_HostAddress}}/ProxyApi/StopProxy
Content-Type: application/json

{
  "listenAddress": "0.0.0.0",
  "listenPort": 25565,

  "targetAddress": "10.0.1.222",
  "targetPort": 25565
}

### Add proxy entry
POST {{TransparentCloudServerProxy.WebDashboard_HostAddress}}/ProxyApi/AddProxy
Content-Type: application/json

{
  "listenAddress": "0.0.0.0",
  "listenPort": 25565,
  "targetAddress": "10.0.1.222",
  "targetPort": 25565
}

### Remove proxy
POST {{TransparentCloudServerProxy.WebDashboard_HostAddress}}/ProxyApi/RemoveProxy
Content-Type: application/json

{
  "listenAddress": "0.0.0.0",
  "listenPort": 25565,
  "targetAddress": "10.0.1.222",
  "targetPort": 25565
}
