@TransparentCloudServerProxy.WebDashboard_HostAddress = https://localhost:7002
@sslVerify = false
@authKey = 0BF5FFE161F87743EA63B6E4884BC2C26D618EFBC2C1A6C3A8E265CF89B2421D

### Get Self
GET {{TransparentCloudServerProxy.WebDashboard_HostAddress}}/User/Get
Accept: application/json
Authorization: Key {{authKey}}

### Create User
POST {{TransparentCloudServerProxy.WebDashboard_HostAddress}}/User/CreateUser
Authorization: Key {{authKey}}
Content-Type: application/json

{
  "Username": "poofy"
}

### Reset Credential
POST {{TransparentCloudServerProxy.WebDashboard_HostAddress}}/User/ResetMyCredential
Authorization: Key {{authKey}}
Content-Type: application/json

### Reset Other's Credential
POST {{TransparentCloudServerProxy.WebDashboard_HostAddress}}/User/ResetCredential
Authorization: Key {{authKey}}
Content-Type: application/json

{
  "Username": "poofy"
}